# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('card_type', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('purchase_details', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('amount', models.IntegerField()),
                ('staff', models.CharField(max_length=255)),
                ('comments', models.TextField()),
            ],
        ),
    ]
