# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 21:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testrun', '0005_auto_20161107_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 6, 21, 44, 49, 21967, tzinfo=utc)),
        ),
    ]
