# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 22:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testrun', '0009_auto_20161107_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='GST',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 6, 22, 9, 49, 44108, tzinfo=utc)),
        ),
    ]
