# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 22:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testrun', '0023_auto_20161107_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='processed',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Processed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 6, 22, 34, 7, 55984, tzinfo=utc)),
        ),
    ]
