# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 04:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testrun', '0036_auto_20161107_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='company',
            new_name='supplier',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='comments',
        ),
        migrations.AddField(
            model_name='transaction',
            name='wfm_job_number',
            field=models.CharField(default='001', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 28, 4, 4, 3, 426512, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='staff',
            field=models.CharField(default='', max_length=255),
        ),
    ]
