# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 22:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testrun', '0039_auto_20161129_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 28, 22, 22, 28, 959413, tzinfo=utc)),
        ),
    ]
