# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 02:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrun', '0046_auto_20161129_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 29, 13, 28, 38, 963728)),
        ),
    ]
