# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 03:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testrun', '0047_auto_20161129_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 29, 3, 22, 15, 216008, tzinfo=utc)),
        ),
    ]
