# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 04:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrun', '0050_auto_20161129_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 29, 15, 25, 23, 27661)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_transaction',
            field=models.CharField(max_length=200),
        ),
    ]
