# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 08:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testrun', '0051_auto_20161129_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 29, 8, 47, 46, 270568, tzinfo=utc)),
        ),
    ]
