# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrun', '0053_auto_20161130_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card_type',
            old_name='type',
            new_name='card_type',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='client',
            new_name='staff',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_created',
            field=models.DateTimeField(default='29/11/16'),
        ),
    ]
