# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testrun', '0057_auto_20161130_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client',
            new_name='client_name',
        ),
    ]
