# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testrun', '0058_auto_20161130_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff',
            new_name='staff_name',
        ),
    ]
