# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrun', '0059_auto_20161130_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_created',
            field=models.DateTimeField(default='30/11/16'),
        ),
    ]
