# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 03:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testrun', '0061_auto_20161130_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_name',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='staff_name',
            new_name='staff',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 30, 3, 47, 45, 224789, tzinfo=utc)),
        ),
    ]
