# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 04:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testrun', '0062_auto_20161130_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 30, 4, 9, 10, 578075, tzinfo=utc)),
        ),
    ]
