# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 04:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testrun', '0064_auto_20161130_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 30, 4, 36, 48, 461720, tzinfo=utc)),
        ),
    ]
